### PR TITLE
Create sip-310.md

### PR DESCRIPTION
**Pull request by Synthquest**
When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing Draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Review by kaleb-keny — APPROVED** [review]

**Comment by kaleb-keny** [comment]
hey @Synthquest  would you be open please to changing it to an sccp and just lower the max open interest limit to zero, it's much easier then winding down the market tbh.... Which will happen eventually with futures perps v2

**Comment by kaleb-keny** [comment]
https://sips.synthetix.io/sccp/sccp-303/ this is the parameter `maxMarketValueUSD`

**Comment by Synthquest** [comment]
@kaleb-keny not sure how this is typically done but i submitted a new PR here:

https://github.com/Synthetixio/SIPs/pull/1275

**Comment by kaleb-keny** [comment]
thank you

**Pull request closed without merging**
