### PR TITLE
Update website and README to reflect workflow changes in SIP-130

### PR DESCRIPTION
**Pull request by lukevs**
I used the language from SIP-130 where possible

### CODE REVIEW

**Review by justinjmoses — APPROVED** [review]
Looks great - thanks for the PR!

**Comment by jmomx** [comment]
@justinjmoses 

https://twitter.com/kaiynne/status/1394437841413820416?s=20

@lukevs and I decided to split the bounty 50/50 as I got the change in first but he improved on  my PR.

How would we collect?

**Comment by kaiynne** [comment]
hey @jmomx @lukevs apologies I think this was dropped I posted on twitter but I think you probably missed it https://twitter.com/kaiynne/status/1397101416020267013?s=21

**Comment by jmomx** [comment]
https://twitter.com/jmo_mx/status/1414943252210274304?s=20

**Pull request merged**
