### PR TITLE
Create SIP-0.md

### PR DESCRIPTION
**Pull request by noam99**
When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

The PR edits only existing Draft PRs.
The build passes.
Your Github username or email address is listed in the 'author' header of all affected PRs, inside .
If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by kaleb-keny** [comment]
hey please use https://pr.synthetix.io/

**Comment by noam99** [comment]
I’m trying, but it keeps giving me errors, and I can't ask for support because I’m blocked from your Discord for some reason.

What can I do?

From: kaleb ***@***.***>
Date: Monday, 19 February 2024 at 08:54
To: Synthetixio/SIPs ***@***.***>
Cc: NoamMo99 ***@***.***>, Author ***@***.***>
Subject: Re: [Synthetixio/SIPs] Create SIP-0.md (PR #1842)

hey please use https://pr.synthetix.io/

**Comment by kaleb-keny** [comment]
Hmmm @noam99 what are you trying to do?

**Comment by kaleb-keny** [comment]
what is your discord id?

**Comment by noam99** [comment]
598600693271756802

I think they already tried to unban me but it didn’t work. I think its related to my phone number but can you try again to unlock me?

Thanks

From: kaleb ***@***.***>
Date: Wednesday, 21 February 2024 at 15:46
To: Synthetixio/SIPs ***@***.***>
Cc: NoamMo99 ***@***.***>, Mention ***@***.***>
Subject: Re: [Synthetixio/SIPs] Create SIP-0.md (PR #1842)

what is your discord id?

**Comment by kaleb-keny** [comment]
try once more

**Comment by noam99** [comment]
﻿It works now! Thanks a lot


From: kaleb ***@***.***>
Date: Wednesday, 21 February 2024 at 17:09
To: Synthetixio/SIPs ***@***.***>
Cc: NoamMo99 ***@***.***>, Mention ***@***.***>
Subject: Re: [Synthetixio/SIPs] Create SIP-0.md (PR #1842)

try once more

**Pull request closed without merging**
