### PR TITLE
SIP-298 update Status to Approved

### PR DESCRIPTION
**Pull request by cavalier-eth**
When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing Draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by kaleb-keny** [comment]
this has neither been presented no approved 😓

**Comment by cavalier-eth** [comment]
has not been presented yet

**Comment by cavalier-eth** [comment]
> this has neither been presented no approved 😓

sorry missed this comment

**Comment by cavalier-eth** [comment]
closed until presented

**Pull request closed without merging**
