### PR TITLE
sip-344

### PR DESCRIPTION
**Pull request by noahlitvin**

### CODE REVIEW

**Review by cavalier-eth — APPROVED** [review]

**Comment by kaleb-keny** [comment]
hey @cavalier-eth @noahlitvin is this ready for merging & presentation this week?

**Review by kaleb-keny — APPROVED** [review]

**Comment by kaleb-keny** [comment]
hmmm this si quite old actually

**Comment by kaleb-keny** [comment]
i assume this isn't ready @noahlitvin ?

**Comment by kaleb-keny** [comment]
closing it @noahlitvin let me know if you want to take it up again

**Pull request closed without merging**
