### PR TITLE
create sccp-305

### PR DESCRIPTION
**Pull request by cavalier-eth**
When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing Draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by kaleb-keny** [comment]
hey @cavalier-eth network can only be one of :
- `Ethereum`
- `Optimism`
- `Ethereum & Optimism`

**Comment by cavalier-eth** [comment]
done

> hey @cavalier-eth network can only be one of :
> 
> * `Ethereum`
> * `Optimism`
> * `Ethereum & Optimism`

**Comment by kaleb-keny** [comment]
hey @cavalier-eth 
```
    'status must be one of the following values: Draft, Feasibility, SC_Review_Pending, Vote_Pending, Approved, Implemented, Rejected, Deprecated'
   ```
   one more change needed

**Comment by kaleb-keny** [comment]
So not <Draft> but Draft

**Comment by kaleb-keny** [comment]
hey @cavalier-eth please add `type: Governance` to the header

**Review by kaleb-keny — APPROVED** [review]

**Pull request merged**
