### PR TITLE
SIP-351: Transaction cost based rewards

### PR DESCRIPTION
**Pull request by leomassazza**
When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing Draft PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by cavalier-eth** [comment]
added a sip number so i could reference it elsewhere

**Comment by cavalier-eth** [comment]
i have no idea why this is failing the test for network...

**Comment by kaleb-keny** [comment]
closed as being included in https://github.com/Synthetixio/SIPs/pull/1832

**Comment by kaleb-keny** [comment]
thank you @leomassazza  for writing it up, 🙏🏼

**Pull request closed without merging**
