### PR TITLE
Sip-draft-Delegatr-Security-Improvement.md

### PR DESCRIPTION
**Pull request by Gasman404**
When opening a pull request to submit a new SIP, please use the suggested template: https://github.com/Synthetixio/SIPs/blob/master/sip-X.md

We have a GitHub bot that automatically merges some PRs. It will merge yours immediately if certain criteria are met:

 - The PR edits only existing WIP PRs.
 - The build passes.
 - Your Github username or email address is listed in the 'author' header of all affected PRs, inside <triangular brackets>.
 - If matching on email address, the email address is the one publicly listed on your GitHub profile.

### CODE REVIEW

**Comment by Gasman404** [comment]
Security question was asked in discord - on if this would raise a vulnerability for SNXLink or similar services to withdraw funds

I suggest that the address that sUSD would be sent to(likely the same as the delegator address) be set in mintr by the main SNX wallet

This way, there is no risk possible of funds being withdrawn to unwanted addresses

**Comment by Gasman404** [comment]
I'd also add that I am not specific on whether the feature request is for 
sUSD minted to arrive in the delegation wallet
or
For the ability to withdraw sUSD from the main SNX wallet

It is more so about achieving the end goal of not having to accesss the main SNX wallet when new sUSD is minted in order to hedge. The specifics i feel can be better addressed by the dev team

**Comment by hav-noms** [comment]
@Gasman404 you can already delegate exchanging for sUSD hedging management  https://sips.synthetix.io/sips/sip-14.

We see the releasing of the sUSD to the delegate as a security risk as the delegator might be a 3rd party service of which would then have full custody over your sUSD. Right now all funds SNX and sUSD minted are always under the custody of the cold storage wallet but can be managed by the delegate via exchangeOnBehalf which is exchanged into the owners cold storage wallet. If the delegate goes rouge the funds are lost.

**Comment by Gasman404** [comment]
> 
> 
> @Gasman404 you can already delegate exchanging for sUSD hedging management https://sips.synthetix.io/sips/sip-14.
> 
> We see the releasing of the sUSD to the delegate as a security risk as the delegator might be a 3rd party service of which would then have full custody over your sUSD. Right now all funds SNX and sUSD minted are always under the custody of the cold storage wallet but can be managed by the delegate via exchangeOnBehalf which is exchanged into the owners cold storage wallet. If the delegate goes rouge the funds are lost.

@hav-noms 

Hi Clint
I am aware of being able to delegate exchanging to synthetix exchange

The issue that is this does not allow 
a) external hedging of those synths - which is essential to the success of the stablecoins. There is not much point for mintrs to keep all the stablecoins to themselves since then the public is unable to use them for trading
b) Mintrs are not able to LP their minted coins without accessing the cold wallet - which means users who only use delegatr  are not able to carry out the full set of weekly tasks if $SNX has gone up & they have to mint more sUSD

In regards to the security risk - if this was an additional option when setting up delegation in mintr - only users who desire this feature will enable it
That way, users who use automated services will not have any risk - as it is not enabled
But users who manually hedge but still desire to keep their SNX in a cold wallet that is distributed & rarely unlocked can have a higher level of security without sacrifice

If it is technically feasible - a good way to do it would be to allow minting of new sUSD to arrive at the delegated wallet
This way, it limits the features available which also limits the risk - users can mint to the delegated wallet - but not withdraw synths from the main SNX wallet

If this would be possible - I see it increasing the security for mintrs
Synths can only be minted to the delegated wallet if this has been set as an additional step in mintr. This would be for users who manually hedge & LP their synths - which is likely what most large SNX holders do

The end result is that as a mintr - I would no longer have to access the cold wallet every week, and it could be a true cold storage wallet - which if setup with distributed multisig - provides a much higher level of security for mintrs with a large amount of $SNX . I could not access the SNX wallet for 2 years and still be a mintr with no sacrifices & higher security for the whole time. 

In terms of the risk of storing minted synths on the delegated wallet - this would likely be a ledger - which is as secure as most people would like to get for weekly access - the delegated wallet would only have to store 11% of the total value of the SNX minting portfolio

For example:
Users could $100k SNX in multisig distributed cold storage & ~$13k of minted assets on a ledger 
Cuts down risk from $113k to $13k in terms of keys that have to be accessed weekly

I'll end with that I would love to use delegatr for added security & have my SNX in a highly secure cold wallet, but if I have to access the SNX 'cold' wallet weekly anyway, when i need to withdraw minted sUSD to LP/hedge externally - this totally defeats the point of using delegatr in the first place

**Comment by kaiynne** [comment]
This functionality introduces too much risk for the delegation use case. A better solution would be to take the previously discussed staking pools and implement that functionality.

**Pull request closed without merging**
