### PR TITLE
Create sccp-360

### PR DESCRIPTION
**Pull request by 0xrobin2192**
Mass.money referral code/address

### CODE REVIEW

**Comment by kaleb-keny** [comment]
motivation section can't be left empty sir

**Comment by 0xrobin2192** [comment]
Added motivation

**Review by kaleb-keny — APPROVED** [review]

**Review by kaleb-keny — CHANGES_REQUESTED** [review]
would you mind please updating the file to .md 
Screenshot from 2024-10-08 17-42-39

**Comment by 0xrobin2192** [comment]
@kaleb-keny not sure how to resolve this check. it looks like the network is correct. I renamed to sccp-360.md.

**Comment by kaleb-keny** [comment]
can you try `Arbitrum & Base` i need to fix this

**Comment by kaleb-keny** [comment]
let's see i did it on your behalf

**Review by kaleb-keny — APPROVED** [review]

**Pull request merged**
