### PR TITLE
Updating 192 as Implemented

### PR DESCRIPTION
**Pull request by justinjmoses**

### CODE REVIEW

**Review by kaleb-keny — CHANGES_REQUESTED** [review]
hey jj can you please add the below to the header
proposal: >-
  https://snapshot.org/#/snxgov.eth/proposal/QmRxscHxcbdkQQVWYmSWvL6ydD1LYX3LSfBScQ4riDudZU

**Comment by justinjmoses** [comment]
@kaleb-keny don't you mean https://snapshot.org/#/snxgov.eth/proposal/0x3a85dc3e70ca5f06d23fa84abbff03c08b90092b4c3262b069c0894e3361340f ?

**Comment by kaleb-keny** [comment]
yes you are right, i don't know why the vote hash is different for this one you know 🤔  ... All the voting hashes are in this format `QmR....` except this one which starts with 0x....
and what i logged into the contract was this `QmRxscHxcbdkQQVWYmSWvL6ydD1LYX3LSfBScQ4riDudZU` https://etherscan.io/tx/0xefa4a22b51dffeb4bbd3de9ed1334a6968d9a57768f3d32d8f3327cff2aa4ea5 which i had obtained  from here https://cloudflare-ipfs.com/ipfs/QmRxscHxcbdkQQVWYmSWvL6ydD1LYX3LSfBScQ4riDudZU

**Comment by justinjmoses** [comment]
updated. rfal

**Comment by kaleb-keny** [comment]
sorry to raise this again @justinjmoses  but the format might not be correct, as you can't see the vote here https://sips-50avkzltr-synthetixio.vercel.app/sips/sip-192/ similar to how you see it normally https://sips-50avkzltr-synthetixio.vercel.app/sips/sip-190/

This could be due to needing to do add the arrow after proposal followed by dash
proposal: >-
https://snapshot.org/#/snxgov.eth/proposal/0x3a85dc3e70ca5f06d23fa84abbff03c08b90092b4c3262b069c0894e3361340f

**Comment by justinjmoses** [comment]
No worries. RFAL

**Review by kaleb-keny — APPROVED** [review]
the vote still doesn't show up unfortunately
https://sips-azrh8xmu0-synthetixio.vercel.app/sips/sip-192/
I've approved it, and will setup another vote, and request council to vote on it and update the link because I feel that this vote wasn't setup the way it's supposed to, causing issues in the sip site displaying the vote

**Review by kaleb-keny — CHANGES_REQUESTED** [review]
Can you please use this link @justinjmoses  I've submitted a revote, given the old one isn't properly accounted for, since it doesn't show up on the staking site nor is it saved into the contract
https://snapshot.org/#/snxgov.eth/proposal/Qmb9MiztqMWBkFgmXB2MTVHkxM7uachCkfAQxdUvKo2YXW

**Comment by justinjmoses** [comment]
try now @kaleb-keny

**Comment by kaleb-keny** [comment]
Sorry for the late reply, it works fine now... although i do see a conflict

**Review by kaleb-keny — APPROVED** [review]

**Pull request merged**
